[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="Session" type="freemarker.ext.servlet.HttpSessionHashModel" --]
[#-- @ftlvariable name="Request" type="freemarker.ext.servlet.HttpRequestHashModel" --]
[#-- @ftlvariable name="RequestParameters" type="freemarker.ext.servlet.HttpRequestParametersHashModel" --]
[#-- @ftlvariable name="Math" type="java.lang.Math" --]
[#-- @ftlroot "" --]
[#import 'layout.ftl' as layout]
[#import '/spring.ftl' as spring]
[#import '/com/slyak/web/support/freemarker/slyak.ftl' as slyak]
[#import '/com/slyak/web/support/freemarker/bootstrap/bootstrap.ftl' as bootstrap]
[#import '/com/slyak/web/support/freemarker/ace/ace.ftl' as ace]
[#import '/com/slyak/web/support/freemarker/sockjs/sockjs.ftl' as sockjs]